name: drawing_env
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - flask
  - hdf5=1.10.2
  - opencv=3.4.2
  - python=3.7
  - pytorch=1.7.1
  - scikit-image
  - scikit-learn
  - scipy
  - sqlite
  - torchaudio
  - torchvision=0.8.2
  - iopath
  - omegaconf
  - pip:
    - google-auth
    - google-auth-oauthlib
    - h5py==2.10.0
    - keras-preprocessing==1.1.2
    - matplotlib
    - numpy
    - tensorboard
    - tensorflow==2.3.2
