name: drawing_env2
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch=1.10.2
  - torchvision=0.11.3
  - torchaudio
  - cudatoolkit=11.3
  - cudnn
  - tensorflow-gpu=2.4.1
  - pillow=8.0.0
  - keras=2.4.3
  - opencv
  - h5py=2.10.0
  - hdf5
  - flask
  - scikit-image=0.18.3
  - scikit-learn
  - scipy
  - sqlite
  - iopath=0.1.8
  - omegaconf
  - google-auth
  - google-auth-oauthlib
  - matplotlib
  - ipython
  - python-lmdb
  - natsort
  - pip:
      - dotted
#    - keras-preprocessing==1.1.2
#    - tensorboard
#    - tensorflow-gpu==2.2.0
#    - keras==2.3.1

# detectron2 설치
# pip install 'git+https://github.com/facebookresearch/detectron2.git'
# pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html
